version: "2"
services:
  app:
    build: ./server/app
    links:
      - db
    ports:
      - "5003:5000"
  db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d/:ro
  frontend:
    build: ./frontend
    ports:
        - "3003:3000"